mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cuckoo.pomelo.common.dao.entity

# 通用Mapper配置
mapper:
  mappers:
    - io.mybatis.mapper.Mapper
  not-empty: true
  identity: SQLITE